%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
# These are taken from the Camera Information in Python API of ZED
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 524.650390625
Camera.fy: 524.650390625
Camera.cx: 636.3681030273438
Camera.cy: 359.5227966308594

Camera.k1: 0.0
Camera.k2: 0.0
Camera.k3: 0.0
Camera.p1: 0.0
Camera.p2: 0.0


Camera.bFishEye: 0

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline in meters times fx
Camera.bf: 62.92245016 # 119.9321517944336 * 524.65039

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Depth map values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

Viewer.pangolin: 1
Viewer.rviz: 1
Viewer.readlocalobject: 0
Viewer.show_object3d_frame: 1

#--------------------------------------------------------------------------------------------
# PointCloud Mapping
#--------------------------------------------------------------------------------------------
PointCloudMapping.Resolution: 0.01

#---------------------------------------------------------------------------------------------
# Semantic Mapping
#---------------------------------------------------------------------------------------------
Semantic.Model: 0 # Yolov5: 0
Semantic.ModelPath: "/home/lacie/slam_ws/src/junbot_planner/object_slam/config/Model"
Semantic.ObjectAssociation: 0 # Cudoid_3d: 0, PointCloud_Segmentation: 1
Semantic.ObjectOptimize: 0

#--------------------------------------------------------------------------------------------
# OctoMap Parameters
#--------------------------------------------------------------------------------------------
octoMap.res: 0.05

#--------------------------------------------------------------------------------------------
# Dynamic point
#--------------------------------------------------------------------------------------------
Dynamic.flow: 10.0

#--------------------------------------------------------------------------------------------
# 3D cuboid
#--------------------------------------------------------------------------------------------
IE.rows: 18
IE.cols: 18
IE.P_occ: 0.6
IE.P_free: 0.4
IE.P_prior: 0.5
IE.Threshold: 5

#--------------------------------------------------------------------------------------------
# MapPublisher
#--------------------------------------------------------------------------------------------
# 1: robot_camera tf; 2: use imu
ConstraintType: 1
Trobot_camera.qx: 0.0003
Trobot_camera.qy: 0.8617
Trobot_camera.qz: -0.5072
Trobot_camera.qw: -0.0145
Trobot_camera.tx: 0.0 #-0.6832
Trobot_camera.ty: 0.0 #2.6909
Trobot_camera.tz: 1.7373

